### ISSUE TITLE
Εγκατάσταση Module

### ISSUE THREAD

**Issue by lakhslakakos** [merentitis/11888_GR_lookup#1]
Προσωπικά ευχαριστώ για την προσφορά σου
Μετά την αντιγραφή του module (source-11888_GR_lookup.module) /var/www/html/admin/modules/superfecta/sources
Που το ορίζουμε ακόμα ?

Το όρισα στο module.sig

Αλλά μου εμφανίζει το εξής

Module: "CID Superfecta", File: "module.sig check failed! Bad Signature, Tampered! ([GNUPG:] BADSIG 86CE877469D2EAD9 FreePBX Mirror 1 (Module Signing - 2014/2015) )"

**Comment by merentitis** [comment]
Παρακαλώ!
Επειδή δε θυμάμαι πως το είχα περάσει και το είχα φτιάξει αρκετά βιαστικά - γιαυτό απουσιάζει και το documentation, δοκίμασε να το βάλεις πάνω απο καποιο από τα υπάρχοντα - φαντάζομαι δε χρησιμοποιείς τα περισσότερα.
Θυμήσου να αλλάξεις το class στο script (line 18). Φαντάζομαι θα χρειαστεί reload και το module

**Comment by lakhslakakos** [comment]
Ευχαριστώ για την περαιτέρω βοήθειά σου...
Λειτούργησε!!!!
- Μοναδικό πρόβλημα, το module το βλέπει ως unsigned ;( 
Πρόβλημα αισθητικής UI...

**Comment by merentitis** [comment]
Χαίρομαι!
Αυτό δε το γλυτώνουμε, θα πρέπει να στείλω pull request στους devs για να το συμπεριλάβουν στο πακέτο τους, αλλά δυστυχώς έχω παλιότερη έκδοση freebpx + πιθανώς του module οπότε έχει δουλίτσα μέχρι να φτάσω εκεί και δυστυχώς ελάχιστο χρόνο από την πλευρά μου για να ασχοληθώ!
